name: Generate Dats
on:
  schedule:
    - cron: "*  */12  * * *"
    workflow_dispatch:
 jobs:
   build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platne/snk@master
        id: snake-gif
     with:
         github_user_name: saif007s
         svg_out_path: dist/github-contribution-grid-snake.svg
    -uses: crazy-max/ghaction-github-pages@v2.1.2
     with:
         target_branch: output
         build_dir: dist
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
